kind: pipeline
type: docker
name: default

steps:

  - name: get-branch-version
    image: smoothify/drone-semantic-release
    pull: always
    settings:
      dry_run: true
      git_credentials: { from_secret: git_password }
      git_user_name: { from_secret: git_user }
      git_user_email: { from_secret: git_email }
      tags_build: true
    when:
      event:
        - push

  - name: build-branch-image
    image: plugins/docker
    settings:
      repo: smoothify/drone-helm-version-bump
      username: {from_secret: docker_username}
      password: {from_secret: docker_password}
      cache_from:
        - smoothify/drone-helm-version-bump:latest
    when:
      event:
        - push

  - name: release-branch
    image: smoothify/drone-semantic-release
    pull: always
    settings:
      dry_run: false
      git_credentials: { from_secret: git_password }
      git_user_name: { from_secret: git_user }
      git_user_email: { from_secret: git_email }
      changelog: true
      package_json: true
    when:
      event:
        - push
